### ISSUE TITLE
Error on installation 

### ISSUE THREAD

**Issue by omarsawalhah** [lschilde/Sharing_APEX_SERT_22_2#1]
I had this error on installing SERT
== SV_SEC_COMPATIBILITY_RULE
set concat on
    *
ERROR at line 17:
ORA-06550: line 17, column 5:
PL/SQL: ORA-00922: missing or invalid option
ORA-06550: line 17, column 1:
PL/SQL: SQL Statement ignored
ORA-06550: line 18, column 6:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:
;

**Comment by lschilde** [comment]
Hi omarsawalhah, appreciate for reporting this above all. 

can you be more specific which script did you install it with? Installation is best done using ins_auto_setup.sql script. I used is from SQL Developer and it worked fine for me.

**Comment by lschilde** [comment]
Try please uninstalling if it APEX_SERT schema is there and run it again... it is hard to tell from here without more info

**Comment by lschilde** [comment]
There are really two scripts to look into ins.sql and in_auto_setup.sql 

first one stands for manual entry installation where second one is automated. 

Only thing to be aware at this stage is -> db_conn_string maybe needs to be changed before you start.

**Comment by andyhardy** [comment]
The error is raised in the file cfg\sv_sec_compatibility_rule.sql - it's missing a block 'end' statement.

**Comment by lschilde** [comment]
Thanks Andy, I just when through all versions as I spotted the same for APEX 23.1 installation. ;) 

workaround for now can be to execute manually (this is after installation of APEX SERT finished)
```
DECLARE 
 l_compatibility_mode varchar2(5);
BEGIN
 select snippet 
    into l_compatibility_mode 
  from SV_SERT_230100.sv_sec_snippets 
  where snippet_key = 'COMPATIBILITY_MODE'; 

SV_SERT_230100.sv_sec_import.attribute_value(
  p_attribute_key         => 'SV_SET_COMPATIBILITY_MODE',
  p_attribute_set_key     => 'DEFAULT',
  p_value                 => l_compatibility_mode,
  p_result                => 'PASS',
  p_active_flag           => 'Y'
  );
END;
```

Of course replacing SV_SERT_XXXXXX with your version

**Comment by lschilde** [comment]
To touch on where this error comes from ..... it used to be part of original code which I have updated but it seems like it has been executing at the wrong time during the installation script. 

What I have done to overcome that is I introduce a new script but as Andy pointed out there was a bug in not having the end; line in my script hence even this second error would pop up. For the time being you can fix it with a manual execution of the code in my previous comment. 

On 07/06/2023 I have detected and fixed this issue will be pushing changes across the board of versions as soon as I test all installs.
