### ISSUE TITLE
UNINS.SQL refers to wrong esert user

### ISSUE THREAD

**Issue by andyhardy** [lschilde/Sharing_APEX_SERT_22_2#4]
Line 60 should read:

`define esert_user                  = 'SV_SERT_220200'`

**Comment by lschilde** [comment]
Thanks Andy for picking this up.... idea was that people should read the script before running it. ;)
Else people can remove their existing installation version of SERT which is sometimes not what you want when you have long running systems with exceptions in them etc....

**Comment by andyhardy** [comment]
> Thanks Andy for picking this up.... idea was that people should read the script before running it. ;) Else people can remove their existing installation version of SERT which is sometimes not what you want when you have long running systems with exceptions in them etc....

That's OK!

I spotted that error whilst trying to track down the others to do with invalid PROMPT statements and missing/invalid null.sql files causing errors to appear in the installation log when trying to work out why my installation doesn't run.

**Comment by lschilde** [comment]
closing the ticket
